apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-pdl-proxy-q1
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-pdl-proxy-alerts
      rules:
        - alert: Applikasjon nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-pdl-proxy-q1"} == 0
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen er nede"
            summary: "App {{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom

        - alert: Applikasjonen har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-pdl-proxy-q1"}[5m])) by (container) > 2
          for: 2m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "App {{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom

        - alert: Høy andel error i logger
          expr: sum by(log_app, log_pod_name, log_namespace) (floor(increase(logd_messages_total{log_app="sokos-pdl-proxy", log_level="Error"}[2m]))) > 2
          for: 2m
          annotations:
            action: "`kubectl logs {{ $labels.log_pod_name }} -n {{ $labels.log_namespace }}`"
            summary: "Høy andel error i logger for app {{ $labels.log_app }} feiler i namespace {{ $labels.log_namespace }}"
          labels:
            namespace: okonomi
            severity: danger
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom

        - alert: Høy andel warning i logger
          expr: sum by(log_app, log_pod_name, log_namespace) (floor(increase(logd_messages_total{log_app="sokos-pdl-proxy", log_level="Warning"}[2m]))) > 2
          for: 2m
          annotations:
            action: "`kubectl logs {{ $labels.log_pod_name }} -n {{ $labels.log_namespace }}`"
            summary: "Høy andel warning i logger for app {{ $labels.log_app }} feiler i namespace {{ $labels.log_namespace }}"
          labels:
            namespace: okonomi
            severity: warning
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom

        - alert: Høy andel HTTP serverfeil (5xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"5.*", app="sokos-pdl-proxy"}[3m])) > 2
          for: 2m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`.
                      Sjekk loggene for å se hvorfor dette feiler."
            action: "`kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}`"
          labels:
            namespace: okonomi
            severity: danger
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom

        - alert: Høy andel HTTP klientfeil (4xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"4.*", status!~"404", app="sokos-pdl-proxy"}[3m])) > 2
          for: 2m
          annotations:
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`. 
                      Sjekk loggene for å se hvorfor dette feiler"
            action: "`kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}`"
          labels:
            namespace: okonomi
            severity: danger
            sokos_pdl_proxy_type: sokos-pdl-proxy
            alert_type: custom


---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-pdl-proxy-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-pdl-proxy-slack
spec:
  receivers:
    - name: sokos-pdl-proxy-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-prod'
          iconEmoji: ':alert:'
          username: 'Alert dev-gcp-q1'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_pdl_proxy_type"
        matchType: "="
        value: "sokos-pdl-proxy"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-pdl-proxy-receiver
    repeatInterval: 2m
