apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-pdl-proxy-q1
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 25
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: utbetalingsreskontro
          cluster: dev-fss
          namespace: okonomi
        - application: oppdragz
          cluster: dev-fss
          namespace: okonomi
    outbound:
      external:
        - host: pdl-api-q1.dev-fss-pub.nais.io
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  ingresses:
    - https://sokos-pdl-proxy-q1.intern.dev.nav.no
  env:
    - name: PDL_URL
      value: https://pdl-api-q1.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api-q1/.default"
