apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-pdl-proxy-q2
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 25
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://sokos-pdl-proxy-q2.dev.adeo.no
  env:
    - name: PDL_HOSTNAME
      value: https://modapp-q2.adeo.no/pdl/api/v1/organisasjon
