apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-pdl-proxy
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 25
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
    accessPolicy:
      inbound:
        rules:
          - application: utbetalingsreskontro
            cluster: dev-fss
            namespace: okonomi
          - application: oppdragz
            cluster: dev-fss
            namespace: okonomi
      outbound:
        external:
          - host: pdl-api.dev-fss-pub.nais.io

  webproxy: true
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://sokos-pdl-proxy.dev.intern.nav.no
  env:
    - name: PDL_CLIENT_ID
      value: dev-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.nais.preprod.local/graphql
    - name: USE_AUTHENTICATION
      value: "true"
    - name : ALLOW_LIST_PDLPROXY
      value: utbetalingsreskontro,oppdragz
