apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-pdl-proxy
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 25
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: utbetalingsreskontro
          cluster: prod-fss
          namespace: okonomi
        - application: oppdragz
          cluster: prod-fss
          namespace: okonomi
      outbound:
        external:
          - host: pdl-api.prod-fss-pub.nais.io
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  liveness:
    path: /internal/is_alive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
    - https://sokos-pdl-proxy.intern.nav.no
  env:
    - name: PDL_CLIENT_ID
      value: prod-fss.pdl.pdl-api
    - name: PDL_URL
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: USE_AUTHENTICATION
      value: "true"
