apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-pdl-proxy
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: utbetalingsreskontro
          cluster: dev-fss
          namespace: okonomi
        - application: oppdragz
          cluster: dev-fss
          namespace: okonomi
    outbound:
      external:
        - host: pdl-api.dev-fss-pub.nais.io
      rules:
        - application: logging
          namespace: nais-system
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 512Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  ingresses:
    - https://sokos-pdl-proxy.intern.dev.nav.no

  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # PDL
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
