name: Deploy alerts
on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-dev-q1.yaml'
      - '.nais/alerts-prod.yaml'

permissions:
  contents: "write"
  id-token: "write"

jobs:
  deploy-dev:
    name: Deploy alerts to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts-dev.yaml

  deploy-dev-q1:
    name: Deploy alerts to dev-q1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts-dev-q1.yaml

  deploy-prod:
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts-prod.yaml