name: Deploy alerts
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'Dockerfile'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.github/workflows/build-pr.yml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/deploy.yaml'
      - '.github/workflows/manual-deploy-dev.yaml'
      - '.github/workflows/manual-deploy-q1.yaml'
      - '.github/dependabot.yml'

jobs:
  deploy-dev:
    name: Deploy alerts to dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/alerts-dev.yaml

  deploy-prod:
    name: Deploy alerts to prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy to prod
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts-prod.yaml