name: Deploy alerts

on:
  push:
    branches:
      - main
    paths:
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-dev-q1.yaml'
      - '.nais/alerts-prod.yaml'

permissions:
  contents: "write"
  id-token: "write"

jobs:
  deploy-dev:
    name: Deploy to dev-gcp
    uses: navikt/moby-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/alerts-dev.yaml

  deploy-dev-q1:
    name: Deploy to dev-gcp
    needs: deploy-dev
    uses: navikt/moby-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: dev-gcp
      resource: .nais/alerts-dev-q1.yaml

  deploy-prod:
    name: Deploy to prod-gcp
    needs: [ deploy-dev, deploy-dev-q1 ]
    uses: navikt/moby-gha-workflows/.github/workflows/nais-alert-deploy.yaml@main
    with:
      cluster: prod-gcp
      resource: .nais/alerts-prod.yaml