name: Deploy alarmer
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'Dockerfile'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.github/workflows/build-pr.yml'
      - '.github/workflows/manual-deploy-dev.yaml'
      - '.github/workflows/manual-deploy-q1.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/build-test-push-deploy.yaml'

jobs:
  deploy-alerts-dev:
    name: Deploy alarmer til prod
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut kode
        uses: actions/checkout@v3
      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/alerts.yaml